require 'mobiletest'

spec = Gem::Specification.find_by_name("mobiletest")
import "#{spec.gem_dir}/lib/mobiletest/android/Fastfile"

PACKAGE = "com.shopify.buy"
ANDROID_PROJECT_PATH='MobileBuy'
BASE_EMULATOR = {
  name: 'shift-21',
  port: '5560'
}

platform :android do
  desc "Run CI"
  lane :ci do
    setup_emulator
    tests
    release
    clean_emulator
  end

  desc "Run Tests"
  lane :tests do
    run_gradle_tests({
      android_project_path: ANDROID_PROJECT_PATH,
      gradle_command: 'clean :buy:connectedAndroidTest -PdisablePreDex',
      artifact_upload_paths: [ 'MobileBuy/buy/build/outputs/androidTest-results/connected/' ],
      android_package: PACKAGE
    })
  end

  desc "Build Release"
  lane :release do
    run_gradle_tests({
      android_project_path: ANDROID_PROJECT_PATH,
      gradle_command: ':buy:archiveReleasePackage',
      artifact_upload_paths: [ 'MobileBuy/buy/build/distributions/' ],
      android_package: PACKAGE
    })
  end

  # By defining start/cleanup down here as lanes,
  # we get free logging and formatting
  desc "Start Emulator with params"
  lane :setup_emulator do
    start_emulator(BASE_EMULATOR)
  end

  desc "Cleanup Emulator"
  lane :clean_emulator do
    cleanup_emulator(emulator: BASE_EMULATOR, android_package: PACKAGE)
  end
end
